name = "knutamregistry"
uuid = "c59a0a09-053a-4810-b6d5-76bd653ef6cd"
repo = "git@github.com:KnutAM/knutamregistry.git"
description = "Knut Andreas' personal registry"

[packages]
952767cb-328b-455d-a479-bf972ef6c2fa = { name = "MaterialModelCalibration", path = "M/MaterialModelCalibration" }
cccc85d9-b314-494a-8960-1c57145c81d1 = { name = "PNNMaterial", path = "P/PNNMaterial" }
d9eb1dd9-fd0a-4339-a954-2bc895d829ff = { name = "ConstitutiveDriver", path = "C/ConstitutiveDriver" }