name = "knutamregistry"
uuid = "c59a0a09-053a-4810-b6d5-76bd653ef6cd"
repo = "git@github.com:KnutAM/knutamregistry.git"
description = "Knut Andreas' personal registry"

[packages]
83aa5b51-0588-403c-85e4-434ec185aae7 = { name = "Newton", path = "N/Newton" }
cccc85d9-b314-494a-8960-1c57145c81d1 = { name = "PNNMaterial", path = "P/PNNMaterial" }
