name = "knutamregistry"
uuid = "c59a0a09-053a-4810-b6d5-76bd653ef6cd"
repo = "git@github.com:KnutAM/knutamregistry.git"
description = "Knut Andreas' personal registry"

[packages]
83aa5b51-0588-403c-85e4-434ec185aae7 = { name = "Newton", path = "N/Newton" }
952767cb-328b-455d-a479-bf972ef6c2fa = { name = "MaterialModelCalibration", path = "M/MaterialModelCalibration" }
af893363-701d-44dc-8b1e-d9a2c129bfc9 = { name = "MaterialModelsBase", path = "M/MaterialModelsBase" }
cccc85d9-b314-494a-8960-1c57145c81d1 = { name = "PNNMaterial", path = "P/PNNMaterial" }
