name = "knutamregistry"
uuid = "c59a0a09-053a-4810-b6d5-76bd653ef6cd"
repo = "git@github.com:KnutAM/knutamregistry.git"
description = "Knut Andreas' personal registry"

[packages]
0d3df087-75fa-4f06-888e-118033dd1b70 = { name = "FE2Materials", path = "F/FE2Materials" }
4b8708f2-a3c1-4548-bedd-a9fc7399e47a = { name = "PorousMedia", path = "P/PorousMedia" }
5314c346-72d0-4bc2-b258-70d19dafa834 = { name = "Steel", path = "S/Steel" }
56e8be39-93f0-4086-9711-ae554a367806 = { name = "MatModFit", path = "M/MatModFit" }
79314e9b-2e6f-4d6d-a72d-515aa2604984 = { name = "FESolvers", path = "F/FESolvers" }
83aa5b51-0588-403c-85e4-434ec185aae7 = { name = "Newton", path = "N/Newton" }
952767cb-328b-455d-a479-bf972ef6c2fa = { name = "MaterialModelCalibration", path = "M/MaterialModelCalibration" }
9f696fae-cea5-48c9-9654-130ac15c79c7 = { name = "EquationDiscovery", path = "E/EquationDiscovery" }
af893363-701d-44dc-8b1e-d9a2c129bfc9 = { name = "MaterialModelsBase", path = "M/MaterialModelsBase" }
b3282f9b-607f-4337-ab95-e5488ab5652c = { name = "MechanicalMaterialModels", path = "M/MechanicalMaterialModels" }
cccc85d9-b314-494a-8960-1c57145c81d1 = { name = "PNNMaterial", path = "P/PNNMaterial" }
d9eb1dd9-fd0a-4339-a954-2bc895d829ff = { name = "ConstitutiveDriver", path = "C/ConstitutiveDriver" }
dc10c695-e18c-49e2-887a-ef9f22cfa888 = { name = "EduMaterialModels", path = "E/EduMaterialModels" }
e7aa30d1-f8c7-4c87-b6be-97e395ec50ad = { name = "FerriteProblems", path = "F/FerriteProblems" }
f0450e97-3c57-4e4a-8020-cfce828c3bbe = { name = "FerriteNeumann", path = "F/FerriteNeumann" }
fd21fc07-c509-4fe1-9468-19963fd5935d = { name = "FerriteAssembly", path = "F/FerriteAssembly" }
